device:
  BAUDRATE:                     57600
  GRIPPER_ID:                   100
  CTRL_ID:                      1
  DEVICENAME:                   "/dev/ttyUSB0"
  # DEVICENAME:                   "COM7"

  HOMING_CURRENT:               70
  CLOSING_CURRENT:              70

workspace:
  thumb:                        [134, 342]
  duo:                          [147, 238]
  MAX_CTRL_CUR:                 100
  # PID:                          [250, 0, 30]
  CTRL_INIT_POS:                1700
  CUR_LIMIT:                    [-600, 600]

control_table:
  ADDR_TORQUE_ENABLE:           64
  ADDR_LED:                     65
  ADDR_CONTROL_MODE:            11
  ADDR_PRESENT_POSITION:        132
  ADDR_PRESENT_CURRENT:         126
  ADDR_CURRENT_LIMIT:           38

  ADDR_HOMING_OFFSET:           20


  ADDR_GOAL_CURRENT:            102

  ADDR_GOAL_POSITION:           116
  ADDR_POSITION_P_GAIN:         84
  ADDR_POSITION_I_GAIN:         82
  ADDR_POSITION_D_GAIN:         80

  ADDR_MAX_POSITION_LIMIT:      48
  ADDR_MIN_POSITION_LIMIT:      52